LTO_ENABLE = yes
VIA_ENABLE = yes
VIAL_ENABLE = yes

VIAL_INSECURE = yes

RGB_MATRIX_ENABLE = yes
VIALRGB_ENABLE = yes

MIDI_ENABLE = no

QMK_SETTINGS = no
TAP_DANCE_ENABLE = no
COMBO_ENABLE = yes
KEY_OVERRIDE_ENABLE = no
REPEAT_KEY_ENABLE  = no
